stages:
  - build

build-java8:
  stage: build
  image: maven:3-jdk-8-alpine
  script: "mvn install -B"

build-java10:
  stage: build
  image: maven:3-jdk-11
  script: "echo 'deb https://dl.bintray.com/sbt/debian /' | tee -a /etc/apt/sources.list.d/sbt.list && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && apt update && apt install apt-transport-https && apt update && apt install sbt && mvn install -B -P sbt -DskipTests"
