stages:
  - build
  - package

services:
  - docker:dind
  
  
build-java8:
  stage: build
  image: maven:3-jdk-8-alpine
  script: "mvn install -B && tar cvfz sparkler-jdk8.tgz ./sparkler-app/bundles ./sparkler-app/target ./resources ./bin ./conf ./sparkler-ui"
  artifacts:
    paths:
    - ./sparkler-jdk8.tgz



build-master:
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  stage: package
  dependencies:
    - build-java8
  script:
    - mkdir ./build
    - tar xvfz sparkler-jdk8.tgz -C ./build
    - docker build --pull -t "$CI_REGISTRY_IMAGE/sparkler" -f sparkler-deployment/docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/sparkler"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/solr" -f sparkler-deployment/docker/Dockerfile.solr .
    - docker push "$CI_REGISTRY_IMAGE/solr"
  only:
    - master

build:
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  stage: package
  dependencies:
    - build-java8
  script:
    - mkdir ./build
    - tar xvfz sparkler-jdk8.tgz -C ./build
    - docker build --pull -t "$CI_REGISTRY_IMAGE/sparkler:$CI_COMMIT_REF_SLUG" -f sparkler-deployment/docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/sparkler:$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE/solr:$CI_COMMIT_REF_SLUG" -f sparkler-deployment/docker/Dockerfile.solr .
    - docker push "$CI_REGISTRY_IMAGE/solr:$CI_COMMIT_REF_SLUG"
  except:
    - master



