name: Scala CI

on:
  push:
    branches: [ mvn2sbt ]
  pull_request:
    branches: [ mvn2sbt ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run submit package
      run: sbt package assembly -Dsparkprovided=true
      working-directory: sparkler-core
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy Submit to Databricks
      run: ./deploy.sh
      working-directory: sparkler-core
      env:
        DATABRICKS_HOST: https://kli-mmit.cloud.databricks.com
        DATABRICKS_TOKEN: dapi88de017d8ab1fe80afe5691c1e786185
    - name: Run full package
      run: sbt clean package assembly -Dsparkprovided=false
      working-directory: sparkler-core
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to databricks
      run: ./deploy.sh standalone
      working-directory: sparkler-core
      env:
        DATABRICKS_HOST: https://kli-mmit.cloud.databricks.com
        DATABRICKS_TOKEN: dapi88de017d8ab1fe80afe5691c1e786185
