name: Sparkler Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13.0.1
      - name: Build with Maven
        working-directory: ./sparkler-core
        run: mvn -B package --file pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: uscdatascience/sparkler:latest
          file: sparkler-core/sparkler-deployment/docker/Dockerfile
          context: ./sparkler-core
