name: Scala CI

on:
  push:
    branches: [ mvn2sbt ]
  pull_request:
    branches: [ mvn2sbt ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run package
      run: sbt package

