name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13.0.1
      - name: Build with Maven
        working-directory: ./sparkler-core
        run: mvn -B package --file pom.xml

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v@2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: uscdatascience/sparkler:latest
          tag_with_ref: true
          file: sparkler-core/sparkler-deployment/docker/Dockerfile
          push: true
          context: ./sparkler-core
